const rowToApplication = (row) => ({
  id:               row.id,
  firstName:     row.first_name,
  lastName:      row.last_name,
  middleInitial: row.middle_initial,
  suffix:       row.suffix,
  name:             row.name,
  email:            row.email,
  phone:            row.phone,
  franchise:        row.franchise,
  status:           row.status,
  date:             row.date,
  address:          row.address,
  dob:              row.dob,
  civilStatus:      row.civil_status,
  spouseName:       row.spouse_name,
  spouseOccupation: row.spouse_occupation,
  spouseDob:        row.spouse_dob,
  dependents:       row.dependents,
  telephone:        row.telephone,
  tin:              row.tin,
  education:        row.education
    ? (typeof row.education === "string" ? JSON.parse(row.education) : row.education)
    : [],
  involvement:      row.involvement,
  equity:           row.equity,
  investment:       row.investment,
  fundSource:       row.fund_source,
  otherBusiness:    row.other_business,
  location:         row.location,
  familyDepend:     row.family_depend,
  marketArea:       row.market_area,
  startDate:        row.start_date,
  dateSigned:       row.date_signed,
  paymentMode:      row.payment_mode,
  gender:           row.gender,
  nationality:      row.nationality,
  employmentType:   row.employment_type,
  yearsEmployer:    row.years_employer,
  income:           row.income,
  employerName:     row.employer_name,
  businessAddress:  row.business_address,
  position:         row.position,
  businessNature:   row.business_nature,
  idType:           row.id_type,
  idImage:          row.id_image,
  letterOfIntent:   row.letter_of_intent,
});

module.exports = { rowToApplication };